CREATE TABLE IF NOT EXISTS "report_rdi" (
	"id" serial PRIMARY KEY NOT NULL,
	"numero_rdi" text NOT NULL,
	"descrizione_rdi" text,
	"nome_file_pif_if" text,
	"codifica_documento" text,
	"stato_documento" text,
	"divisione" text,
	"centro_costo" text,
	"ultima_pif_approvata" text,
	"descrizione_pif_if" text,
	"data_caricamento" date,
	"utente_caricamento" text,
	"fornitore" text,
	"roi" text,
	"data_invio_roi" date,
	"data_rifiuto_roi" date,
	"data_approvazione_roi" date,
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "report_rdi_numero_rdi_unique" UNIQUE("numero_rdi")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "verbali_apertura" (
	"id" serial PRIMARY KEY NOT NULL,
	"num_bdo" text,
	"descrizione" text,
	"nome_file" text,
	"codifica_documento" text,
	"stato_verbale" text,
	"periodo_competenza" text,
	"divisione" text,
	"centro_costo" text,
	"fornitore" text,
	"utente_caricamento_fornitore" text,
	"data_firma_fornitore" date,
	"roi" text,
	"data_inserimento_verbale_non_sottomesso" date,
	"data_sottomissione_verbale_fornitore" date,
	"data_firma_roi" date,
	"data_rifiuto_roi" date,
	"data_invio_roi" date,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "verbali_sal" (
	"id" serial PRIMARY KEY NOT NULL,
	"num_bdo" text,
	"descrizione" text,
	"nome_file" text,
	"codifica_documento" text,
	"stato_verbale" text,
	"periodo_competenza" text,
	"conforme" text,
	"motivo_conformita" text,
	"criticita" text,
	"motivazione_criticita" text,
	"livelli_servizio_rispettati" text,
	"divisione" text,
	"centro_costo" text,
	"fornitore" text,
	"utente_caricamento_fornitore" text,
	"data_firma_fornitore" date,
	"roi" text,
	"data_inserimento_verbale_non_sottomesso" date,
	"data_sottomissione_verbale_fornitore" date,
	"data_firma_roi" date,
	"data_rifiuto_roi" date,
	"data_invio_roi" date,
	"updated_at" timestamp DEFAULT now()
);
