CREATE TABLE IF NOT EXISTS "report_pdc" (
	"id" serial PRIMARY KEY NOT NULL,
	"num_bdo" text,
	"posizione_bdo" text,
	"descrizione_posizione" text,
	"importo_posizione" numeric(15, 4),
	"codice_pdc" text,
	"periodo_pdc" text,
	"data_creazione" date,
	"utente_caricamento" text,
	"codifica_documento" text,
	"stato_pdc" text,
	"divisione" text,
	"centro_costo" text,
	"fornitore_rti" text,
	"roi" text,
	"data_invio_roi" date,
	"data_rifiuto_roi" date,
	"data_approvazione_roi" date,
	"fornitore_prestazione" text,
	"service_line" text,
	"tipo_fornitura" text,
	"rdi" text,
	"posizione_rdi" text,
	"subappalto" text,
	"subappaltatore" text,
	"costo_subappalto" numeric(15, 4),
	"updated_at" timestamp DEFAULT now()
);
